---
language: python
python: "3.9"

# Use the new container infrastructure
sudo: required

before_install:
 - sudo useradd -d /home/ansible-test-user ansible-test-user
 - sudo mkdir /home/ansible-test-user
 - sudo chown ansible-test-user:ansible-test-user /home/ansible-test-user
 - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

# addons:
#   apt:
#     packages:
#     - python-pip

install:
  - PATH=$HOME/.local/bin:$PATH
  - export PATH
  - poetry install

script:
  - poetry run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
